package de.alphastudio.coronet2.ui

internal val ledCategoryNames = listOf("IDLE", "PRINT", "PAUSE", "ERROR", "FINISH", "OTHER")

internal val ledAnimationCatalog = listOf(
    listOf("Rainbow", "Fireplace", "Ocean", "StarPulse", "Meteor", "Twinkle", "Larson", "Lava", "Gradient", "Plasma", "SectionBreathe", "Snow", "ColorWipe", "Moonlight", "Tetris", "Running", "Bubbles", "Drift", "Candle", "Starfield", "AuroraRibbon", "RainbowGlitter", "SoftComet", "Kaleidoscope", "BreathingOrbit", "PixelFireflies", "CosmicDust", "TheaterGlow", "TidalPool", "NeonDrift", "ReadyBreath", "AmbientClock", "TemperatureIdle", "LastPrintEcho", "WifiBeacon", "SleepyCore", "MaterialShelf", "StatusRing", "ChamberLantern", "PrintReadySplit", "CalmTide", "ZenGarden", "DuskHorizon", "SilkFlow", "NorthernSleep", "DewSparks", "LampGlow", "CloudDrift", "QuietComet", "SectionCalm"),
    listOf("ProgressBar", "Laser", "Wave", "Thermal", "Stripes", "ProgressPulse", "Comet", "ActiveSection", "Running", "Breathe", "Wipe", "Shimmer", "Bicolor", "Thermometer", "Snake", "RainbowProgress", "Heartbeat", "DnaHelix", "PixelRain", "Orbit", "ExtruderSpark", "LayerScan", "HeatRipple", "FilamentComets", "ProgressTheater", "NozzleTrace", "BuildPlate", "MicroSteps", "FlowWave", "ToolheadOrbit", "ThermalBalance", "MaterialCore", "HeatSoak", "StabilityMonitor", "LayerEngine", "TimeTunnel", "ChamberAura", "FilamentFlow", "ProcessStack", "HealthBeacon", "FinishPressure", "DualTempMeter", "LayerPulse", "ToolpathEcho", "ThermalRibbon", "InfillGrid", "FilamentBeads", "TimeFlow", "StepperTicks", "CalmBuild", "QualityGuard", "NozzleHeat", "LayerFill"),
    listOf("Amber", "Hazard", "Freeze", "Radar", "Heartbeat", "ProgressBar", "Crossfade", "Phase", "YellowWhite", "WatchfulEyes", "AmberStrobe", "Zigzag", "Neon", "Hourglass", "AmberWave", "Bounce", "SlowComet", "Spinner", "MorseWait", "BlueBreathe", "SoftHold", "AmberTheater", "BreathingDots", "WaitingRipple", "ParkingLights", "DimSparks", "SlowScan", "FrozenGold", "ClockTick", "CalmOrbit", "HoldingPattern", "BreathingAmber", "ResumeGate", "TempKeepalive", "SoftAttention", "OperatorWait", "FrozenLayer", "FilamentHold", "DoNotTouch", "HeatHoldSplit", "CalmDown", "StillWater", "SoftLantern", "HoldOrb", "SuspendedLayer", "GentleReminder", "BreathGate", "WaitingRoom", "ToolPark", "ResumeRamp"),
    listOf("Blink", "Sos", "Alarm", "Critical", "Police", "RedBreathe", "Heartbeat", "Strobe", "RedWave", "Xenon", "Siren", "Thunder", "Countdown", "Glitch", "AlarmChase", "DangerStripe", "PulseAlert", "Redout", "Emergency", "Meltdown", "Crash", "RedTheater", "FaultRipple", "HotZone", "PanicComets", "Lockdown", "WarningTicks", "BreachScan", "FaultSparks", "RedJuggle", "Evacuate", "CauseHint", "StackLight", "SmartHeartbeat", "LocationSplit", "BlackoutFlash", "RecoveryWait", "SirenScan", "DiagnosticBits", "ServiceBeacon", "SafeShutdown", "CalmAlert", "FaultLocator", "ThermalCut", "NetworkLost", "ServiceCode", "Containment", "SafeBreath", "Escalation", "RepairBeacon", "CoolingAlarm"),
    listOf("Sweep", "Rainbow", "Pulse", "Filament", "Fireworks", "Curtain", "Confetti", "GoldRain", "StrobeParty", "BouncingBalls", "RainbowExplosion", "Disco", "Heart", "ColorSpiral", "Sparkle", "Champagne", "WipeOut", "Fill", "Waterfall", "Starburst", "VictoryLap", "GoldTheater", "RibbonDance", "TrophyGlow", "StarGlitter", "DualComets", "Applause", "PrismBloom", "PixelToast", "CrownChase", "CooldownProgress", "PrintSignature", "SmartApplause", "TakeMe", "CoolToTouch", "LastLayerGlow", "GalleryMode", "FilamentFireworks", "InspectionLight", "QuietPride", "CalmDone", "SilkUnveil", "GoldenHour", "Starfall", "SignatureSweep", "InspectReady", "PrintEcho", "SoftApplause", "CooldownAura", "ShowcaseLoop"),
    listOf("Matrix", "Candle", "StaticRainbow", "NeonClub", "Synthwave", "Jellyfish", "Snow", "Sunset", "Volcano", "Techno", "DragonBlood", "Aurora", "Cyberpunk", "Nebula", "Submarine", "Pride", "Plasma", "BouncingBalls", "CopCar", "StrobeParty", "Sunrise", "OceanDepth", "Radiation", "Pastel", "Electric", "RainbowPulse", "Carnival", "NeonSign", "MotionDetect", "RetroTv", "Crystal", "FireAndIce", "LaserGrid", "GalaxySpin", "CometTwins", "DeepSeaPulse", "SolarWind", "PixelCircus", "MintBreeze", "RubyScan", "ArcadeChase", "Stardust", "IceCave", "FireworkTrail", "ChromaRing", "GhostLight", "ToxicWave", "CopperSpark", "Blueprint", "MagmaFlow", "CandyStripe", "QuantumDots", "ShowroomLoop", "AudioReactive", "WeatherMood", "ClockAurora", "FilamentGallery", "Maintenance", "Calibration", "HeatmapDemo", "ProductHero", "NightLight", "FocusMode", "PartyLock", "RetroTerminal", "PlasmaCore", "StatusMirror", "TimeBreath", "SectionDemo", "CinemaIdle", "LuxuryAmbient", "SpectrumScanner", "CalmDown", "Meditation", "Bioluminescence", "LiquidGlass", "EmberRoom", "NeonRain", "SolarEclipse", "CrystalPrism", "RoyalAurora", "DataStream"),
)

internal val soundScenarioNames = listOf("PRINT START", "PRINT FINISH", "ERROR", "PAUSE", "IDLE")
internal val ledSectionNames = listOf("RIGHT", "CENTER", "LEFT", "INSIDE")
internal val calibrationColorNames = listOf("RED", "ORANGE", "YELLOW", "GREEN", "CYAN", "BLUE", "VIOLET", "MAGENTA")
internal val pandaModeNames = listOf("OFF", "AUTO", "PREHEAT", "TEMPER", "FORCED", "DRY")
internal val pandaDryPresetNames = listOf("PLA", "PETG", "ABS / ASA", "TPU", "NYLON / PA", "PC", "CUSTOM")

internal fun animationDisplayName(identifier: String): String = identifier
    .replace(Regex("(?<=[a-z0-9])(?=[A-Z])"), " ")
    .replace("Dna", "DNA")
    .replace("Wifi", "WiFi")
